# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(19131E)
$foreground = rgb(DEB9D5)
$color0 = rgb(403A46)
$color1 = rgb(18052D)
$color2 = rgb(310815)
$color3 = rgb(330813)
$color4 = rgb(370A18)
$color5 = rgb(672051)
$color6 = rgb(792966)
$color7 = rgb(C892BB)
$color8 = rgb(8C6683)
$color9 = rgb(20063D)
$color10 = rgb(420B1B)
$color11 = rgb(440B19)
$color12 = rgb(4A0E20)
$color13 = rgb(8A2B6C)
$color14 = rgb(A13688)
$color15 = rgb(C892BB)
