# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(20181E)
$foreground = rgb(ECDAEA)
$color0 = rgb(473F45)
$color1 = rgb(260721)
$color2 = rgb(41061D)
$color3 = rgb(43061C)
$color4 = rgb(46061C)
$color5 = rgb(700716)
$color6 = rgb(977192)
$color7 = rgb(DCC2D8)
$color8 = rgb(9A8897)
$color9 = rgb(32092C)
$color10 = rgb(570826)
$color11 = rgb(590826)
$color12 = rgb(5D0825)
$color13 = rgb(95091D)
$color14 = rgb(C996C2)
$color15 = rgb(DCC2D8)
