# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #ECDAEA
background         #20181E
cursor             #A17188

active_tab_foreground     #20181E
active_tab_background     #ECDAEA
inactive_tab_foreground   #ECDAEA
inactive_tab_background   #20181E

active_border_color   #ECDAEA
inactive_border_color #20181E
bell_border_color     #260721

color0      #473F45
color1		#260721
color2		#41061D
color3		#43061C
color4		#46061C
color5		#700716
color6		#977192
color7		#DCC2D8
color8		#9A8897
color9		#32092C
color10		#570826
color11		#590826
color12		#5D0825
color13		#95091D
color14		#C996C2
color15		#DCC2D8
