# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #DEB9D5
background         #19131E
cursor             #906278

active_tab_foreground     #19131E
active_tab_background     #DEB9D5
inactive_tab_foreground   #DEB9D5
inactive_tab_background   #19131E

active_border_color   #DEB9D5
inactive_border_color #19131E
bell_border_color     #18052D

color0      #403A46
color1		#18052D
color2		#310815
color3		#330813
color4		#370A18
color5		#672051
color6		#792966
color7		#C892BB
color8		#8C6683
color9		#20063D
color10		#420B1B
color11		#440B19
color12		#4A0E20
color13		#8A2B6C
color14		#A13688
color15		#C892BB
