# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #B4CBFD
background         #101116
cursor             #6486F6

active_tab_foreground     #101116
active_tab_background     #B4CBFD
inactive_tab_foreground   #B4CBFD
inactive_tab_background   #101116

active_border_color   #B4CBFD
inactive_border_color #101116
bell_border_color     #050D1C

color0      #38393E
color1		#050D1C
color2		#1031B3
color3		#1E4FBB
color4		#1E4FBC
color5		#1E4FBC
color6		#1E4FBC
color7		#8BACF4
color8		#6178AB
color9		#071126
color10		#1541EF
color11		#2869FA
color12		#286AFA
color13		#286AFA
color14		#286AFA
color15		#8BACF4
